# Generated by Django 6.0.5 on 2026-09-18 19:48

import atelier.apps.core.validators.image_validator
import atelier.apps.core.validators.validate_cep
import atelier.apps.products.models.product_category_model
import atelier.apps.products.models.product_image_model
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('category_image', models.ImageField(blank=True, default='default/category_img.jpg', help_text='Formatos aceitos: jpg, jpeg ou png. Máx: 5MB.', null=True, upload_to=atelier.apps.products.models.product_category_model.category_image_path, validators=[atelier.apps.core.validators.image_validator.validate_image_file])),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['category_name'],
                'constraints': [models.UniqueConstraint(fields=('category_name',), name='unique_category_name')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='O preço não pode ser negativo')], verbose_name='Preço')),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='O estoque não pode ser negativo')], verbose_name='Estoque')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('categories', models.ManyToManyField(help_text='Uma peça artesanal pode pertencer a mais de uma categoria (ex.: pulseira de cristais → Pulseiras e Cristais).', related_name='products', to='products.productcategory', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductShipping',
            fields=[
                ('product_shipping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_zip_code', models.CharField(default='45201347', max_length=11, validators=[atelier.apps.core.validators.validate_cep.validate_cep], verbose_name='CEP de origem')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0.001, message='O peso deve ser maior que zero')], verbose_name='Peso (kg)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1, message='A altura deve ser maior que zero')], verbose_name='Altura (cm)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1, message='A largura deve ser maior que zero')], verbose_name='Largura (cm)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1, message='O comprimento deve ser maior que zero')], verbose_name='Comprimento (cm)')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantidade padrão de itens deste produto por embalagem, usada como base para a cotação de frete.', validators=[django.core.validators.MinValueValidator(1, message='A quantidade deve ser pelo menos 1')], verbose_name='Quantidade por embalagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='products.product')),
            ],
            options={
                'verbose_name': 'Dados de frete do produto',
                'verbose_name_plural': 'Dados de frete dos produtos',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_image', models.ImageField(upload_to=atelier.apps.products.models.product_image_model.product_image_path, validators=[atelier.apps.core.validators.image_validator.validate_image_file], verbose_name='Imagem')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Imagem principal')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Imagem do produto',
                'verbose_name_plural': 'Imagens dos produtos',
                'ordering': ['display_order', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('product_id',), name='unique_cover_image_per_product')],
            },
        ),
    ]
