# Generated by Django 6.0.5 on 2026-09-22 19:23

import atelier.apps.chat.models.message_attachment_model
import atelier.apps.core.validators.chat_attachment_validator
import atelier.config.storages
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_order_frenet_order_id_order_shipped_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=140, verbose_name='Assunto')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Encerrada')], default='open', max_length=10, verbose_name='Status')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Última mensagem em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('assigned_admin', models.ForeignKey(blank=True, help_text='Quem está cuidando desta conversa no momento. Opcional — qualquer admin pode responder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Admin responsável')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('order', models.ForeignKey(blank=True, help_text='Preenchido quando a conversa é sobre um pedido específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='payments.order', verbose_name='Pedido relacionado')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='Conversa')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('attachment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=atelier.config.storages.PrivateFilesStorage(), upload_to=atelier.apps.chat.models.message_attachment_model.chat_attachment_path, validators=[atelier.apps.core.validators.chat_attachment_validator.validate_chat_attachment_file], verbose_name='Arquivo')),
                ('file_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('document', 'Documento')], max_length=10, verbose_name='Tipo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome original')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamanho (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message', verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['client', '-last_message_at'], name='chat_conver_client__da28d1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', '-last_message_at'], name='chat_conver_status_731933_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read'], name='chat_messag_convers_7d694b_idx'),
        ),
    ]
