# Generated by Django 6.0.5 on 2026-09-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='frenet_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_label_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_service_code',
            field=models.CharField(blank=True, help_text='Service code retornado pela cotação Frenet e escolhido pelo cliente no checkout.', max_length=50, null=True, verbose_name='Código do serviço Frenet'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Aguardando envio'), ('label_generated', 'Etiqueta gerada'), ('shipped', 'Enviado'), ('in_transit', 'Em transporte'), ('delivered', 'Entregue')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
